#!C:\Users\MTS\PycharmProjects\projectStock\venv\Scripts\python.exe
import cgi,cgitb
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>Hello - Second CGI Program</title>")
print("</head>")
print("<body>")
print("<b>Enter a query!!</b>")
print("<form>")
print("<input type='text' name='field'>")
print("<input type='submit'>")
print("</form>")
print("</body>")
print("</html>")